# Generated by Django 5.0.6 on 2024-05-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylist',
            old_name='service',
            new_name='services',
        ),
    ]
