# Generated by Django 5.0.6 on 2024-05-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
