# Generated by Django 5.0.6 on 2024-06-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_service_duration_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='profile',
            field=models.ImageField(null=True, upload_to='stylist_profile/'),
        ),
    ]
