# Generated by Django 5.0.6 on 2024-06-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_stylist_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='stylist_profile/'),
        ),
    ]
