# Generated by Django 5.0.6 on 2024-05-22 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_service_duration_alter_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='stylists',
        ),
        migrations.AddField(
            model_name='service',
            name='stylists',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.stylist'),
        ),
    ]
