# Generated by Django 5.0.6 on 2024-05-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_remove_service_stylists_alter_service_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(max_length=10),
        ),
    ]
